import 'package:json_annotation/json_annotation.dart';
import 'package:twmt/models/common/json_converters.dart';

part 'translation_version.g.dart';

/// Translation version status enumeration
///
/// Simplified status workflow:
/// - pending: Not yet translated
/// - translated: Translation completed and validated
/// - needsReview: Translation has validation errors or warnings
enum TranslationVersionStatus {
  @JsonValue('pending')
  pending,
  @JsonValue('translated')
  translated,
  @JsonValue('needs_review')
  needsReview;

  /// Canonical string stored in the SQLite `translation_versions.status`
  /// column. Mirrors the `@JsonValue` annotations so raw SQL writes/reads
  /// stay in sync with the JSON-serialised path.
  String get toDbValue {
    switch (this) {
      case TranslationVersionStatus.pending:
        return 'pending';
      case TranslationVersionStatus.translated:
        return 'translated';
      case TranslationVersionStatus.needsReview:
        return 'needs_review';
    }
  }
}

/// Source of a translation
///
/// Tracks where the translation came from:
/// - unknown: Legacy data or unspecified source
/// - manual: User manually entered/edited the translation
/// - tmExact: 100% match from Translation Memory
/// - tmFuzzy: Fuzzy match (85-99%) from Translation Memory
/// - llm: Generated by LLM provider
enum TranslationSource {
  @JsonValue('unknown')
  unknown,
  @JsonValue('manual')
  manual,
  @JsonValue('tm_exact')
  tmExact,
  @JsonValue('tm_fuzzy')
  tmFuzzy,
  @JsonValue('llm')
  llm,
}

/// Represents a translation of a unit in a specific language.
///
/// Each translation unit can have multiple versions (one per target language).
/// This model tracks the translated text, quality metrics, and review status.
@JsonSerializable()
class TranslationVersion {
  /// Unique identifier (UUID)
  final String id;

  /// ID of the translation unit being translated
  @JsonKey(name: 'unit_id')
  final String unitId;

  /// ID of the project language this translation belongs to
  @JsonKey(name: 'project_language_id')
  final String projectLanguageId;

  /// The translated text (null if not yet translated)
  @JsonKey(name: 'translated_text')
  final String? translatedText;

  /// Whether the translation was manually edited by a user
  @JsonKey(name: 'is_manually_edited')
  @BoolIntConverter()
  final bool isManuallyEdited;

  /// Current status of the translation
  final TranslationVersionStatus status;

  /// Source of the translation (manual, tm_exact, tm_fuzzy, llm)
  @JsonKey(name: 'translation_source')
  final TranslationSource translationSource;

  /// JSON string containing validation issues (if any)
  @JsonKey(name: 'validation_issues')
  final String? validationIssues;

  /// Schema version of [validationIssues].
  ///
  /// 0 = legacy `List<String>` or `List.toString()` format
  /// 1 = structured `[{rule, severity, message}, ...]` introduced in 2026-04.
  ///
  /// New writes should use version 1; the startup rescan migrates version-0
  /// rows to version 1.
  @JsonKey(name: 'validation_schema_version', defaultValue: 0)
  final int validationSchemaVersion;

  /// Unix timestamp when the version was created
  @JsonKey(name: 'created_at')
  final int createdAt;

  /// Unix timestamp when the version was last updated
  @JsonKey(name: 'updated_at')
  final int updatedAt;

  const TranslationVersion({
    required this.id,
    required this.unitId,
    required this.projectLanguageId,
    this.translatedText,
    this.isManuallyEdited = false,
    this.status = TranslationVersionStatus.pending,
    this.translationSource = TranslationSource.unknown,
    this.validationIssues,
    this.validationSchemaVersion = 0,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Returns true if translation is pending
  bool get isPending => status == TranslationVersionStatus.pending;

  /// Returns true if translation is completed
  bool get isTranslated => status == TranslationVersionStatus.translated;

  /// Returns true if translation needs review (has validation errors/warnings)
  bool get needsReview => status == TranslationVersionStatus.needsReview;

  /// Returns true if the translation has been completed
  bool get isComplete => status == TranslationVersionStatus.translated;

  /// Returns true if the translation has validation issues
  bool get hasValidationIssues =>
      validationIssues != null && validationIssues!.isNotEmpty;

  /// Returns true if the translation is ready for use
  bool get isReadyForUse =>
      isComplete && !hasValidationIssues && translatedText != null;

  /// Returns the translated text or a placeholder
  String get displayText => translatedText ?? '(Not translated)';

  /// Returns a status display string
  String get statusDisplay {
    switch (status) {
      case TranslationVersionStatus.pending:
        return 'Pending';
      case TranslationVersionStatus.translated:
        return 'Translated';
      case TranslationVersionStatus.needsReview:
        return 'Needs Review';
    }
  }

  TranslationVersion copyWith({
    String? id,
    String? unitId,
    String? projectLanguageId,
    String? translatedText,
    bool? isManuallyEdited,
    TranslationVersionStatus? status,
    TranslationSource? translationSource,
    String? validationIssues,
    int? validationSchemaVersion,
    int? createdAt,
    int? updatedAt,
  }) {
    return TranslationVersion(
      id: id ?? this.id,
      unitId: unitId ?? this.unitId,
      projectLanguageId: projectLanguageId ?? this.projectLanguageId,
      translatedText: translatedText ?? this.translatedText,
      isManuallyEdited: isManuallyEdited ?? this.isManuallyEdited,
      status: status ?? this.status,
      translationSource: translationSource ?? this.translationSource,
      validationIssues: validationIssues ?? this.validationIssues,
      validationSchemaVersion:
          validationSchemaVersion ?? this.validationSchemaVersion,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  factory TranslationVersion.fromJson(Map<String, dynamic> json) =>
      _$TranslationVersionFromJson(json);

  Map<String, dynamic> toJson() => _$TranslationVersionToJson(this);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is TranslationVersion &&
        other.id == id &&
        other.unitId == unitId &&
        other.projectLanguageId == projectLanguageId &&
        other.translatedText == translatedText &&
        other.isManuallyEdited == isManuallyEdited &&
        other.status == status &&
        other.translationSource == translationSource &&
        other.validationIssues == validationIssues &&
        other.createdAt == createdAt &&
        other.updatedAt == updatedAt;
  }

  @override
  int get hashCode =>
      id.hashCode ^
      unitId.hashCode ^
      projectLanguageId.hashCode ^
      translatedText.hashCode ^
      isManuallyEdited.hashCode ^
      status.hashCode ^
      translationSource.hashCode ^
      validationIssues.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  String toString() => 'TranslationVersion(id: $id, unitId: $unitId, status: $status, isManuallyEdited: $isManuallyEdited)';
}
