/// Centralized tooltip strings for the TWMT application
///
/// This file contains all tooltip messages used throughout the application.
/// Tooltips provide contextual help when users hover over buttons and controls.
///
/// Organized by feature area for easy maintenance.
class TooltipStrings {
  // Prevent instantiation
  TooltipStrings._();

  // ========== COMMON ACTIONS ==========

  static const String save = 'Save changes';
  static const String cancel = 'Cancel and close';
  static const String delete = 'Delete this item';
  static const String edit = 'Edit this item';
  static const String add = 'Add new item';
  static const String refresh = 'Refresh data';
  static const String clearSearch = 'Clear search';
  static const String close = 'Close';
  static const String copy = 'Copy to clipboard';
  static const String back = 'Go back';

  // ========== MODS SCREEN ==========

  static const String modsRefresh =
      'Rescan Steam Workshop folders for mods containing localization files';
  static const String modsHiddenToggle =
      'Switch between viewing normal and hidden mods';
  static const String modsHideCheckbox =
      'Hide this mod from the main list';
  static const String modsOpenWorkshop =
      'Open this mod on Steam Workshop';
  static const String modsDownloadRequired =
      'Click to delete local file and force a redownload from Steam';
  static const String modsFilterAll = 'Show all mods';
  static const String modsFilterNotImported =
      'Show only mods without translation projects';
  static const String modsFilterNeedsUpdate =
      'Show only mods with pending updates or changes';
  static const String modsImportLocalPack =
      'Import a local .pack file that is not from Steam Workshop';

  // ========== PROJECTS SCREEN ==========

  static const String projectsFilterNeedsUpdate =
      'Show projects requiring attention due to mod source changes';
  static const String projectsFilterIncomplete =
      'Show projects not yet 100% translated in all configured languages';
  static const String projectsFilterHasComplete =
      'Show projects with at least one language fully translated';
  static const String projectsSortName = 'Sort projects alphabetically by name';
  static const String projectsSortDate =
      'Sort projects by most recently updated first';
  static const String projectsSortProgress =
      'Sort projects by overall translation completion percentage';
  static const String projectsOpenSteam =
      'View the original mod on Steam Workshop';
  static const String projectsDelete =
      'Permanently delete this project and all associated data';
  static const String projectsAddLanguage =
      'Add a new target language to this project';
  static const String projectsOpenEditor =
      'Open the Translation Editor for this language';
  static const String projectsDeleteLanguage =
      'Remove this target language and all its translations';

  // ========== TRANSLATION EDITOR ==========

  static const String editorModelSelector =
      'Select the AI model to use for translation';
  static const String editorSkipTm =
      'Skip Translation Memory lookup and send all units directly to the AI model';
  static const String editorSettings =
      'Configure batch size and parallel request settings';
  static const String editorModRule =
      'Create or edit mod-specific translation instructions';
  static const String editorModRuleEdit =
      'Edit mod-specific translation rule';
  static const String editorModRuleAdd =
      'Add mod-specific translation rule';
  static const String editorTranslateAll =
      'Translate all untranslated entries in the project';
  static const String editorTranslateSelected =
      'Translate only the selected entries';
  static const String editorValidate =
      'Run validation checks on all translations and open review screen';
  static const String editorExport =
      'Export translations to a .pack file for in-game use';
  static const String editorFilterPending =
      'Show entries with no translation yet';
  static const String editorFilterTranslated =
      'Show entries with completed translations';
  static const String editorFilterNeedsReview =
      'Show entries flagged for review due to validation issues';
  static const String editorFilterTmExact =
      'Show translations from Translation Memory with 100% source text match';
  static const String editorFilterTmFuzzy =
      'Show translations from Translation Memory with similarity above threshold';
  static const String editorFilterTmLlm =
      'Show translations generated by AI model';
  static const String editorFilterTmManual =
      'Show translations entered or edited manually';
  static const String editorFilterTmNone = 'Show entries with no translation yet';
  static const String editorClearFilters = 'Reset all filters and show all entries';

  // ========== TRANSLATION EDITOR CONTEXT MENU ==========

  static const String editorContextEdit =
      'Open inline editor for the translated text';
  static const String editorContextSelectAll = 'Select all visible rows';
  static const String editorContextForceRetranslate =
      'Send selected entries to AI even if already translated';
  static const String editorContextMarkTranslated =
      'Set selected entries status to Translated';
  static const String editorContextClearTranslation =
      'Remove translated text from selected entries';
  static const String editorContextViewHistory =
      'View all changes made to this translation';
  static const String editorContextViewPrompt =
      'Preview the exact AI prompt that would be sent for this entry';
  static const String editorContextDelete = 'Delete selected translation entries';

  // ========== VALIDATION REVIEW ==========

  static const String validationExportReport =
      'Export validation results to a file';
  static const String validationFilterAll = 'Show all issues';
  static const String validationFilterErrors = 'Show only error-level issues';
  static const String validationFilterWarnings = 'Show only warning-level issues';
  static const String validationAccept =
      'Mark as reviewed and keep the translation';
  static const String validationReject =
      'Clear translation and mark for retranslation';
  static const String validationEditFix =
      'Open dialog to fix the translation';
  static const String validationAcceptAll =
      'Accept all selected issues';
  static const String validationRejectAll =
      'Reject all selected issues';

  // ========== TRANSLATION PROGRESS ==========

  static const String progressStop =
      'Gracefully cancel translation (current batch will complete)';

  // ========== PACK COMPILATION ==========

  static const String compilationNew = 'Create a new compilation pack';
  static const String compilationEdit = 'Modify compilation settings';
  static const String compilationDelete =
      'Remove this compilation configuration (does not delete projects or generated files)';
  static const String compilationGenerate =
      'Regenerate the pack file with current translations';
  static const String compilationSelectAll = 'Select all available projects';
  static const String compilationDeselectAll = 'Clear all project selections';
  static const String compilationCopyBBCode =
      'Copy Steam Workshop BBCode links to clipboard';
  static const String compilationSave =
      'Save compilation configuration without generating';
  static const String compilationSaveAndGenerate =
      'Save configuration and generate the combined pack file';

  // ========== GLOSSARY ==========

  static const String glossaryNew = 'Create a new glossary';
  static const String glossaryImport = 'Import glossary entries from file';
  static const String glossaryExport = 'Export glossary entries to file';
  static const String glossaryDelete = 'Delete this glossary';
  static const String glossaryAddEntry = 'Add a new term pair';
  static const String glossaryEditEntry = 'Edit this term pair';
  static const String glossaryDeleteEntry = 'Remove this term pair';

  // ========== TRANSLATION MEMORY ==========

  static const String tmImport =
      'Import translation memory entries from a TMX file';
  static const String tmExport =
      'Export translation memory entries to a TMX file';
  static const String tmCleanup =
      'Remove unused entries to reduce database size';
  static const String tmCopyEntry =
      'Copy source and target text to clipboard';
  static const String tmDeleteEntry =
      'Remove this entry from Translation Memory';

  // ========== SETTINGS ==========

  static const String settingsDetectAllGames =
      'Scan Steam installation to automatically find game paths';
  static const String settingsDetectGame =
      'Auto-detect this game installation path';
  static const String settingsBrowsePath = 'Manually select folder';
  static const String settingsTestRpfm =
      'Validate RPFM executable and display version';
  static const String settingsDefaultPath = 'Use the default path';
  static const String settingsDefaultSchema =
      'Set to the standard RPFM schema path';
  static const String settingsDetectWorkshop =
      'Auto-detect Steam Workshop content folder';
  static const String settingsTestConnection =
      'Test API connection with current key';
  static const String settingsAddLanguage = 'Add a custom language';
  static const String settingsDeleteLanguage =
      'Remove this custom language';
  static const String settingsSetDefaultLanguage =
      'Set as default language for new projects';
  static const String settingsAddIgnoredText =
      'Add a new source text to skip during translation';
  static const String settingsResetIgnoredDefaults =
      'Delete all entries and restore default ignored texts';
  static const String settingsReanalyze =
      'Scan all translations and fix status inconsistencies';
  static const String settingsClearModCache =
      'Remove stale pending changes badges from projects';
  static const String settingsAddRule = 'Add a new translation instruction';
  static const String settingsEditRule = 'Modify this translation rule';
  static const String settingsDeleteRule = 'Remove this translation rule';
  static const String settingsToggleRule = 'Enable or disable this rule';
  static const String settingsSetDefaultModel =
      'Set as default model for this provider';
  static const String settingsToggleModel =
      'Enable or disable this model for use';

  // ========== PROJECT DETAIL ==========

  static const String projectDetailOpenSteam =
      'Open this mod on Steam Workshop';
  static const String projectDetailDeleteProject =
      'Permanently delete this project and all translations';
}
