import 'package:flutter_test/flutter_test.dart';
import 'package:twmt/services/file/parsers/tsv_parser.dart';

void main() {
  group('TsvParser.parseString', () {
    final parser = TsvParser();

    test('skips the RPFM TSV header row (key/text/tooltip)', () {
      const content = 'key\ttext\ttooltip\n'
          '#Loc;1;loc_PackedFile\n'
          'unit_name_1\tSwordsmen\ttrue\n'
          'unit_name_2\tSpearmen\tfalse\n';

      final result = parser.parseString(
        content: content,
        fileName: 'text_en.loc.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(2));
      expect(result.entries[0].key, 'unit_name_1');
      expect(result.entries[0].value, 'Swordsmen');
      expect(result.entries[1].key, 'unit_name_2');
      expect(result.entries[1].value, 'Spearmen');
      // The '#Loc;...' metadata row is consumed as a comment, not an entry.
      expect(result.comments, ['Loc;1;loc_PackedFile']);
    });

    test('skips a two-column key/text header variant', () {
      const content = 'key\ttext\n'
          'greeting_key\tHello\n';

      final result = parser.parseString(
        content: content,
        fileName: 'test.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(1));
      expect(result.entries.single.key, 'greeting_key');
    });

    test('skips header even when metadata comment precedes data rows', () {
      // Header may appear after blank lines; it is still the first data row.
      const content = '\nkey\ttext\ttooltip\n'
          '#Loc;1;loc_PackedFile\n'
          'real_key\tReal value\ttrue\n';

      final result = parser.parseString(
        content: content,
        fileName: 'text_fr.loc.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(1));
      expect(result.entries.single.key, 'real_key');
      expect(result.entries.single.value, 'Real value');
    });

    test('does not drop a legitimate first row that is not the header', () {
      const content = 'unit_name_1\tSwordsmen\ttrue\n'
          'unit_name_2\tSpearmen\tfalse\n';

      final result = parser.parseString(
        content: content,
        fileName: 'text_en.loc.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(2));
      expect(result.entries[0].key, 'unit_name_1');
    });

    test('does not drop a first row whose key is literally "key" but value differs', () {
      const content = 'key\tSome real translation\ttrue\n';

      final result = parser.parseString(
        content: content,
        fileName: 'test.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(1));
      expect(result.entries.single.key, 'key');
      expect(result.entries.single.value, 'Some real translation');
    });

    test('only checks the first data row for the header', () {
      // A row matching the header shape later in the file is kept as data.
      const content = 'first_key\tFirst value\n'
          'key\ttext\ttooltip\n';

      final result = parser.parseString(
        content: content,
        fileName: 'test.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(2));
      expect(result.entries[1].key, 'key');
      expect(result.entries[1].value, 'text\ttooltip');
    });

    test('parses TWMT-format TSV (comments + key/value) unchanged', () {
      const content = '# Generated by TWMT\n'
          '\n'
          'my_key\tMy value\n'
          'other_key\tValue with \\n newline\n';

      final result = parser.parseString(
        content: content,
        fileName: 'export.tsv',
      );

      expect(result, isNotNull);
      expect(result!.comments, ['Generated by TWMT']);
      expect(result.entries, hasLength(2));
      expect(result.entries[0].key, 'my_key');
      expect(result.entries[0].value, 'My value');
      expect(result.entries[1].value, 'Value with \n newline');
    });
  });
}
