import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:twmt/models/common/result.dart';
import 'package:twmt/services/file/models/file_exceptions.dart';
import 'package:twmt/services/file/models/localization_entry.dart';
import 'package:twmt/services/file/parsers/tsv_parser.dart';

void main() {
  group('TsvParser.parseString', () {
    final parser = TsvParser();

    test('skips the RPFM TSV header row (key/text/tooltip)', () {
      const content = 'key\ttext\ttooltip\n'
          '#Loc;1;loc_PackedFile\n'
          'unit_name_1\tSwordsmen\ttrue\n'
          'unit_name_2\tSpearmen\tfalse\n';

      final result = parser.parseString(
        content: content,
        fileName: 'text_en.loc.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(2));
      expect(result.entries[0].key, 'unit_name_1');
      expect(result.entries[0].value, 'Swordsmen');
      expect(result.entries[1].key, 'unit_name_2');
      expect(result.entries[1].value, 'Spearmen');
      // The '#Loc;...' metadata row is consumed as a comment, not an entry.
      expect(result.comments, ['Loc;1;loc_PackedFile']);
    });

    test('skips a two-column key/text header variant', () {
      const content = 'key\ttext\n'
          'greeting_key\tHello\n';

      final result = parser.parseString(
        content: content,
        fileName: 'test.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(1));
      expect(result.entries.single.key, 'greeting_key');
    });

    test('skips header even when metadata comment precedes data rows', () {
      // Header may appear after blank lines; it is still the first data row.
      const content = '\nkey\ttext\ttooltip\n'
          '#Loc;1;loc_PackedFile\n'
          'real_key\tReal value\ttrue\n';

      final result = parser.parseString(
        content: content,
        fileName: 'text_fr.loc.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(1));
      expect(result.entries.single.key, 'real_key');
      expect(result.entries.single.value, 'Real value');
    });

    test('does not drop a legitimate first row that is not the header', () {
      const content = 'unit_name_1\tSwordsmen\ttrue\n'
          'unit_name_2\tSpearmen\tfalse\n';

      final result = parser.parseString(
        content: content,
        fileName: 'text_en.loc.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(2));
      expect(result.entries[0].key, 'unit_name_1');
    });

    test('does not drop a first row whose key is literally "key" but value differs', () {
      const content = 'key\tSome real translation\ttrue\n';

      final result = parser.parseString(
        content: content,
        fileName: 'test.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(1));
      expect(result.entries.single.key, 'key');
      expect(result.entries.single.value, 'Some real translation');
    });

    test('only checks the first data row for the header', () {
      // A row matching the header shape later in the file is kept as data.
      const content = 'first_key\tFirst value\n'
          'key\ttext\ttooltip\n';

      final result = parser.parseString(
        content: content,
        fileName: 'test.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries, hasLength(2));
      expect(result.entries[1].key, 'key');
      expect(result.entries[1].value, 'text\ttooltip');
    });

    test('parses TWMT-format TSV (comments + key/value) unchanged', () {
      const content = '# Generated by TWMT\n'
          '\n'
          'my_key\tMy value\n'
          'other_key\tValue with \\n newline\n';

      final result = parser.parseString(
        content: content,
        fileName: 'export.tsv',
      );

      expect(result, isNotNull);
      expect(result!.comments, ['Generated by TWMT']);
      expect(result.entries, hasLength(2));
      expect(result.entries[0].key, 'my_key');
      expect(result.entries[0].value, 'My value');
      expect(result.entries[1].value, 'Value with \n newline');
    });

    test('preserves significant leading/trailing whitespace in the value '
        '(3-column RPFM row)', () {
      // Total War strings can carry meaningful edge spaces (e.g. the
      // concatenation fragment " of "). The binary .loc parser preserves them,
      // so the TSV path must too.
      const content = 'frag_of\t of \ttrue\n';

      final result = parser.parseString(
        content: content,
        fileName: 'text_en.loc.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries.single.key, 'frag_of');
      expect(result.entries.single.value, ' of ');
    });

    test('strips only a trailing CR (CRLF) from a 2-column value', () {
      const content = 'greeting\tHello\r\n';

      final result = parser.parseString(
        content: content,
        fileName: 'test.tsv',
      );

      expect(result, isNotNull);
      expect(result!.entries.single.value, 'Hello');
    });
  });

  group('TsvParser.parseFileStream', () {
    final parser = TsvParser();
    late Directory tempDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('tsv_parser_stream_');
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    Future<File> writeTsv(String content) async {
      final file =
          File('${tempDir.path}${Platform.pathSeparator}text_en.loc.tsv');
      await file.writeAsString(content);
      return file;
    }

    Future<List<Result<LocalizationEntry, FileParsingException>>> collect(
        String filePath) {
      return parser.parseFileStream(filePath: filePath).toList();
    }

    List<LocalizationEntry> okEntries(
        List<Result<LocalizationEntry, FileParsingException>> results) {
      return [
        for (final r in results)
          if (r.isOk) r.value,
      ];
    }

    test('skips the RPFM TSV header row (key/text/tooltip)', () async {
      final file = await writeTsv(
        'key\ttext\ttooltip\n'
        '#Loc;1;loc_PackedFile\n'
        'unit_name_1\tSwordsmen\ttrue\n'
        'unit_name_2\tSpearmen\tfalse\n',
      );

      final results = await collect(file.path);

      expect(results.every((r) => r.isOk), isTrue,
          reason: 'No errors expected, got: $results');
      final entries = okEntries(results);
      expect(entries, hasLength(2),
          reason: 'Header row must not be yielded as an entry');
      expect(entries[0].key, 'unit_name_1');
      expect(entries[0].value, 'Swordsmen');
      expect(entries[1].key, 'unit_name_2');
      expect(entries[1].value, 'Spearmen');
    });

    test('skips a two-column key/text header variant', () async {
      final file = await writeTsv(
        'key\ttext\n'
        'greeting_key\tHello\n',
      );

      final results = await collect(file.path);

      final entries = okEntries(results);
      expect(entries, hasLength(1));
      expect(entries.single.key, 'greeting_key');
      expect(entries.single.value, 'Hello');
    });

    test('skips header even when blank lines precede it', () async {
      final file = await writeTsv(
        '\nkey\ttext\ttooltip\n'
        '#Loc;1;loc_PackedFile\n'
        'real_key\tReal value\ttrue\n',
      );

      final results = await collect(file.path);

      final entries = okEntries(results);
      expect(entries, hasLength(1));
      expect(entries.single.key, 'real_key');
      expect(entries.single.value, 'Real value');
    });

    test('does not drop a first row whose key is literally "key" but value '
        'differs', () async {
      final file = await writeTsv('key\tSome real translation\ttrue\n');

      final results = await collect(file.path);

      final entries = okEntries(results);
      expect(entries, hasLength(1),
          reason: 'Only the exact RPFM header is skipped, not any "key" row');
      expect(entries.single.key, 'key');
      expect(entries.single.value, 'Some real translation');
    });

    test('only checks the first data row for the header', () async {
      // A row matching the header shape later in the file is kept as data.
      final file = await writeTsv(
        'first_key\tFirst value\n'
        'key\ttext\ttooltip\n',
      );

      final results = await collect(file.path);

      final entries = okEntries(results);
      expect(entries, hasLength(2));
      expect(entries[1].key, 'key');
      expect(entries[1].value, 'text\ttooltip');
    });

    test('parses TWMT-format TSV (comments + key/value) unchanged', () async {
      final file = await writeTsv(
        '# Generated by TWMT\n'
        '\n'
        'my_key\tMy value\n'
        'other_key\tValue with \\n newline\n',
      );

      final results = await collect(file.path);

      expect(results.every((r) => r.isOk), isTrue);
      final entries = okEntries(results);
      expect(entries, hasLength(2));
      expect(entries[0].key, 'my_key');
      expect(entries[0].value, 'My value');
      expect(entries[1].value, 'Value with \n newline');
    });

    test('yields Err for an invalid line but keeps streaming', () async {
      final file = await writeTsv(
        'no_tab_on_this_line\n'
        'good_key\tGood value\n',
      );

      final results = await collect(file.path);

      expect(results, hasLength(2));
      expect(results[0].isErr, isTrue);
      expect(results[1].isOk, isTrue);
      expect(results[1].value.key, 'good_key');
    });

    test('yields Err for a missing file', () async {
      final results = await collect(
          '${tempDir.path}${Platform.pathSeparator}does_not_exist.tsv');

      expect(results, hasLength(1));
      expect(results.single.isErr, isTrue);
    });
  });
}
